"use client";

import { useState } from "react";
import { type useMultiplayerRoom } from "@/components/multiplayer/use-multiplayer-room";

export function MultiplayerLobby({ multiplayer }: { multiplayer: ReturnType<typeof useMultiplayerRoom> }) {
  const [code, setCode] = useState("");
  const [seats, setSeats] = useState(2);
  const { room } = multiplayer;
  if (room) {
    const isHost = room.hostPlayerId === multiplayer.identity.id;
    return <section className="rounded-[1.5rem] border border-violet/15 bg-white p-4 shadow-card" aria-label="Sala multijugador"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-violet">Sala de Laberinto</p><p className="mt-1 font-display text-2xl font-black tracking-[.16em] text-ink">{room.code}</p></div><span className={`rounded-full px-3 py-2 text-xs font-black ${room.status === "PLAYING" ? "bg-leaf/15 text-leaf" : "bg-sun/35 text-ink"}`}>{room.status === "PLAYING" ? "RECORRIDO ACTIVO" : "EN LA SALA"}</span></div><p className="mt-3 text-xs font-bold leading-5 text-ink/65">Comparte el código solo con tu familia o grupo. No hay chat, nombres reales ni mensajes privados.</p><div className="mt-4 grid gap-2">{room.players.filter((player) => player.status !== "LEFT").map((player) => <div key={player.id} className="flex items-center justify-between rounded-xl bg-sky/60 px-3 py-2 text-sm font-bold text-ink"><span>{player.avatar} {player.nickname}{player.id === room.hostPlayerId ? " · anfitrión" : ""}</span><span className={`text-xs ${player.status === "CONNECTED" ? "text-leaf" : "text-ink/45"}`}>{player.status === "CONNECTED" ? "conectado" : "reconectando"}</span></div>)}</div>{multiplayer.error && <p role="alert" className="mt-3 rounded-xl bg-coral/10 p-3 text-xs font-bold text-coral">{multiplayer.error}</p>}<div className="mt-4 flex flex-wrap gap-2">{isHost && room.status === "LOBBY" && <button type="button" onClick={multiplayer.startRoom} className="rounded-xl bg-violet px-4 py-3 text-sm font-extrabold text-white hover:bg-ink focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet/25">Iniciar recorrido</button>}<button type="button" onClick={multiplayer.leaveRoom} className="rounded-xl bg-sky px-4 py-3 text-sm font-extrabold text-ink hover:bg-violet/10 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet/25">Salir de la sala</button></div>{room.status === "LOBBY" && <p className="mt-3 text-xs font-bold text-ink/55">{isHost ? "Cuando el grupo esté listo, inicia el recorrido." : "Espera a que el anfitrión inicie el recorrido."}</p>}</section>;
  }

  return <section className="rounded-[1.5rem] border border-violet/15 bg-white p-4 shadow-card" aria-label="Crear o unirse a una sala"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-violet">Multijugador · beta local</p><h3 className="mt-1 font-display text-xl font-black text-ink">Juega en una sala de 1–4</h3></div><span className={`rounded-full px-3 py-2 text-[10px] font-black uppercase ${multiplayer.connection === "connected" ? "bg-leaf/15 text-leaf" : "bg-ink/5 text-ink/45"}`}>{multiplayer.connection === "connected" ? "Servidor listo" : "Servidor sin conexión"}</span></div><p className="mt-3 text-xs font-bold leading-5 text-ink/65">Crea una sala para tu grupo o escribe un código. Los movimientos del laberinto se sincronizan sin chat ni datos personales.</p><div className="mt-4 flex flex-wrap items-center gap-2"><label className="text-xs font-black text-ink/60" htmlFor="maze-seats">Lugares</label><select id="maze-seats" value={seats} onChange={(event) => setSeats(Number(event.target.value))} className="rounded-xl border border-ink/10 bg-sky px-3 py-2 text-sm font-bold text-ink focus:outline-none focus:ring-4 focus:ring-violet/20"><option value={1}>1 jugador</option><option value={2}>2 jugadores</option><option value={3}>3 jugadores</option><option value={4}>4 jugadores</option></select><button type="button" onClick={() => multiplayer.createRoom(seats)} disabled={multiplayer.connection !== "connected"} className="rounded-xl bg-violet px-4 py-2 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-40 hover:bg-ink focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet/25">Crear sala</button></div><div className="mt-3 flex gap-2"><label className="sr-only" htmlFor="maze-room-code">Código de sala</label><input id="maze-room-code" value={code} onChange={(event) => setCode(event.target.value.toUpperCase().replace(/[^A-Z2-9]/g, "").slice(0, 6))} maxLength={6} placeholder="CÓDIGO" className="min-w-0 flex-1 rounded-xl border border-ink/10 bg-white px-3 py-2 text-center text-sm font-black tracking-[.18em] text-ink outline-none focus:border-violet focus:ring-4 focus:ring-violet/15" /><button type="button" onClick={() => multiplayer.joinRoom(code)} disabled={code.length !== 6 || multiplayer.connection !== "connected"} className="rounded-xl bg-sky px-4 py-2 text-sm font-extrabold text-ink disabled:cursor-not-allowed disabled:opacity-40 hover:bg-violet/10 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet/25">Unirme</button></div>{multiplayer.error && <p role="alert" className="mt-3 rounded-xl bg-coral/10 p-3 text-xs font-bold text-coral">{multiplayer.error}</p>}</section>;
}
