"use client";

import { useState } from "react";
import { CharacterAvatar } from "@/components/character-avatar";
import { type useMultiplayerRoom } from "@/components/multiplayer/use-multiplayer-room";
import { avatarFallbackFor } from "@/lib/characters/catalog";

const positiveMessages = [["great_job", "¡Buen trabajo!"], ["keep_going", "¡Sigue adelante!"], ["you_can_do_it", "¡Tú puedes!"]] as const;

export function MultiplayerLobby({ multiplayer }: { multiplayer: ReturnType<typeof useMultiplayerRoom> }) {
  const [code, setCode] = useState("");
  const [seats, setSeats] = useState(2);
  const { room } = multiplayer;

  if (room) {
    const isHost = room.hostPlayerId === multiplayer.identity.id;
    return <section className="av-panel rounded-[1.5rem] p-4 shadow-card" aria-label="Sala multijugador">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#67e5e0]">Sala de Laberinto</p><p className="mt-1 font-display text-2xl font-black tracking-[.16em] text-[#f5e5b9]">{room.code}</p></div><span className={`rounded-full px-3 py-2 text-xs font-black ${room.status === "PLAYING" ? "bg-[#74e2b0]/15 text-[#74e2b0]" : "bg-[#f5bd4d]/15 text-[#f5cf74]"}`}>{room.status === "PLAYING" ? "RECORRIDO ACTIVO" : "EN LA SALA"}</span></div>
      <p className="mt-3 text-xs font-bold leading-5 text-white/65">Comparte el código solo con tu familia o grupo. Solo se muestran apodos; no hay mensajes privados.</p>
      <div className="mt-4 grid gap-2">{room.players.filter((player) => player.status !== "LEFT").map((player) => <div key={player.id} className="flex items-center justify-between rounded-xl border border-teal-100/15 bg-[#061923]/55 px-3 py-2 text-sm font-bold text-white"><span className="flex min-w-0 items-center gap-2"><CharacterAvatar avatarKey={player.avatar} fallback={avatarFallbackFor(player.avatar)} alt={`Avatar de ${player.nickname}`} imageSizes="28px" className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[#0d5d70]" /><span className="truncate">{player.nickname}{player.id === room.hostPlayerId ? " · anfitrión" : ""}</span></span><span className={`shrink-0 text-xs ${player.status === "CONNECTED" ? "text-[#74e2b0]" : "text-white/45"}`}>{player.status === "CONNECTED" ? "conectado" : "reconectando"}</span></div>)}</div>
      <div className="mt-4 rounded-xl border border-teal-100/15 bg-[#0b3542] p-3"><p className="text-xs font-black uppercase tracking-wide text-[#67e5e0]">Chat seguro de sala</p><p className="mt-1 text-xs font-bold leading-5 text-white/65">Usa una frase positiva. El servidor filtra datos personales y limita mensajes.</p>{multiplayer.chatMessages.length > 0 && <div className="mt-2 grid gap-1" aria-live="polite">{multiplayer.chatMessages.slice(-3).map((message) => <p key={message.id} className="rounded-lg bg-[#061923]/60 px-2 py-1.5 text-xs font-bold text-white/85">{message.author.nickname}: {message.text}</p>)}</div>}<div className="mt-3 flex flex-wrap gap-2">{positiveMessages.map(([key, label]) => <button key={key} type="button" onClick={() => multiplayer.sendPositiveMessage(key)} className="rounded-lg border border-white/15 bg-white/10 px-3 py-2 text-xs font-extrabold text-white hover:bg-white/15 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-teal-100/25">{label}</button>)}</div></div>
      {multiplayer.error && <p role="alert" className="mt-3 rounded-xl bg-coral/10 p-3 text-xs font-bold text-coral">{multiplayer.error}</p>}
      <div className="mt-4 flex flex-wrap gap-2">{isHost && room.status === "LOBBY" && <button type="button" onClick={multiplayer.startRoom} className="av-gold-button rounded-xl px-4 py-3 text-sm font-extrabold focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#f5bd4d]/30">Iniciar recorrido</button>}<button type="button" onClick={multiplayer.leaveRoom} className="rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm font-extrabold text-white hover:bg-white/15 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-teal-100/25">Salir de la sala</button></div>
      {room.status === "LOBBY" && <p className="mt-3 text-xs font-bold text-white/55">{isHost ? "Cuando el grupo esté listo, inicia el recorrido." : "Espera a que el anfitrión inicie el recorrido."}</p>}
    </section>;
  }

  return <section className="av-panel rounded-[1.5rem] p-4 shadow-card" aria-label="Crear o unirse a una sala"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#67e5e0]">Multijugador</p><h3 className="mt-1 font-display text-xl font-black text-[#f5e5b9]">Juega en una sala de 1–4</h3></div><span className={`rounded-full px-3 py-2 text-[10px] font-black uppercase ${multiplayer.connection === "connected" ? "bg-[#74e2b0]/15 text-[#74e2b0]" : "bg-white/10 text-white/45"}`}>{multiplayer.connection === "connected" ? "Servidor listo" : "Servidor sin conexión"}</span></div><p className="mt-3 text-xs font-bold leading-5 text-white/65">Crea una sala para tu grupo o escribe un código. Los movimientos del laberinto se sincronizan sin datos personales.</p><div className="mt-4 flex flex-wrap items-center gap-2"><label className="text-xs font-black text-white/60" htmlFor="maze-seats">Lugares</label><select id="maze-seats" value={seats} onChange={(event) => setSeats(Number(event.target.value))} className="rounded-xl border border-teal-100/20 bg-[#061923]/65 px-3 py-2 text-sm font-bold text-white focus:outline-none focus:ring-4 focus:ring-teal-100/15"><option value={1}>1 jugador</option><option value={2}>2 jugadores</option><option value={3}>3 jugadores</option><option value={4}>4 jugadores</option></select><button type="button" onClick={() => multiplayer.createRoom(seats)} disabled={multiplayer.connection !== "connected"} className="av-gold-button rounded-xl px-4 py-2 text-sm font-extrabold disabled:cursor-not-allowed disabled:opacity-40 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#f5bd4d]/30">Crear sala</button></div><div className="mt-3 flex gap-2"><label className="sr-only" htmlFor="maze-room-code">Código de sala</label><input id="maze-room-code" value={code} onChange={(event) => setCode(event.target.value.toUpperCase().replace(/[^A-Z2-9]/g, "").slice(0, 6))} maxLength={6} placeholder="CÓDIGO" className="min-w-0 flex-1 rounded-xl border border-teal-100/20 bg-[#061923]/65 px-3 py-2 text-center text-sm font-black tracking-[.18em] text-white outline-none placeholder:text-white/35 focus:border-teal-200 focus:ring-4 focus:ring-teal-100/15" /><button type="button" onClick={() => multiplayer.joinRoom(code)} disabled={code.length !== 6 || multiplayer.connection !== "connected"} className="av-teal-button rounded-xl px-4 py-2 text-sm font-extrabold disabled:cursor-not-allowed disabled:opacity-40 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-teal-100/25">Unirme</button></div>{multiplayer.error && <p role="alert" className="mt-3 rounded-xl bg-coral/10 p-3 text-xs font-bold text-coral">{multiplayer.error}</p>}</section>;
}
