import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckIcon } from "@/components/icons";
import { missionOfTheDay } from "@/lib/content";

export const metadata: Metadata = { title: "Misión diaria | Aventura Vida", description: "El reto especial de hoy." };

export default function MissionPage() {
  return (
    <section className="mx-auto max-w-5xl px-4 pb-12 pt-12 sm:px-6 sm:pt-16"><div className="overflow-hidden rounded-[2rem] bg-ink p-6 text-white shadow-lift sm:p-10"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-sun">Misión de hoy</p><h1 className="mt-3 font-display text-5xl font-black tracking-tight sm:text-6xl">{missionOfTheDay.title}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/70">{missionOfTheDay.description}</p></div><div className="grid h-28 w-28 place-items-center rounded-[2rem] bg-sun text-5xl text-ink shadow-card">☀</div></div><div className="mt-8 grid gap-3 border-t border-white/10 pt-6 sm:grid-cols-3"><div className="rounded-xl bg-white/10 p-4"><p className="text-xs font-black uppercase tracking-wide text-white/55">Objetivo</p><p className="mt-2 font-bold">{missionOfTheDay.objective}</p></div><div className="rounded-xl bg-white/10 p-4"><p className="text-xs font-black uppercase tracking-wide text-white/55">Recompensa</p><p className="mt-2 font-bold text-sun">+{missionOfTheDay.rewardXp} XP</p></div><div className="rounded-xl bg-white/10 p-4"><p className="text-xs font-black uppercase tracking-wide text-white/55">Puntos</p><p className="mt-2 font-bold text-sun">+{missionOfTheDay.rewardPoints} puntos</p></div></div></div><div className="mt-10 grid gap-6 md:grid-cols-[1.1fr_.9fr]"><div><h2 className="font-display text-3xl font-black text-ink">¿Cómo funciona?</h2><div className="mt-5 grid gap-3">{["Cada día habrá un desafío diferente.", "Completa juegos para sumar XP, puntos y logros locales.", "Las misiones automáticas y sus recompensas verificadas llegarán con el servidor."].map((step, index) => <div key={step} className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-card"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-violet text-sm font-black text-white">{index + 1}</span><p className="font-bold text-ink">{step}</p><CheckIcon className="ml-auto h-5 w-5 text-leaf" /></div>)}</div></div><aside className="rounded-[1.7rem] bg-[#e9fbf5] p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-leaf">Juego relacionado</p><h2 className="mt-3 font-display text-2xl font-black text-ink">{missionOfTheDay.gameName}</h2><p className="mt-2 text-sm leading-6 text-ink/65">Puedes practicar ya en este minijuego. La concesión automática del bono diario se añadirá al conectar el servidor.</p><Link href={`/juegos/${missionOfTheDay.gameSlug}/jugar`} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-violet hover:underline focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet/25">Jugar ahora <ArrowRight className="h-4 w-4" /></Link></aside></div></section>
  );
}
