"use client";

import { useEffect, useState } from "react";
import { VictoryPanel, useGameCompletion } from "@/components/games/game-shell";

type Tile = number | null;

const sceneSvg = encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 800"><rect width="800" height="800" fill="#aee7f8"/><circle cx="620" cy="144" r="78" fill="#ffe37d"/><path d="M0 220 Q220 30 440 216" fill="none" stroke="#f28381" stroke-width="37"/><path d="M0 276 Q220 85 440 272" fill="none" stroke="#7664e9" stroke-width="32"/><path d="M0 410 Q150 295 384 420 V800 H0Z" fill="#68b96f"/><path d="M800 380 Q620 270 350 432 V800 H800Z" fill="#3f966c"/><path d="M0 585 Q210 515 395 606 Q620 522 800 600 V800 H0Z" fill="#62cfe2"/><path d="M218 520 Q408 404 592 520 L548 658 H260Z" fill="#ffcb91" stroke="#172147" stroke-width="12"/><path d="M245 520 L405 352 L568 520Z" fill="#cf785f" stroke="#172147" stroke-width="12"/><rect x="370" y="520" width="72" height="137" rx="12" fill="#fff1c8" stroke="#172147" stroke-width="12"/><path d="M86 590 q22-35 44 0 q22-35 44 0" fill="none" stroke="#172147" stroke-width="12" stroke-linecap="round"/><path d="M650 600 q18-29 36 0 q18-29 36 0" fill="none" stroke="#172147" stroke-width="12" stroke-linecap="round"/></svg>`);
const sceneUrl = `data:image/svg+xml,${sceneSvg}`;

function createBoard(size: number): Tile[] { return [...Array(size * size - 1).keys(), null]; }
function solved(board: Tile[]): boolean { return board.every((tile, index) => tile === (index === board.length - 1 ? null : index)); }
function neighbors(blank: number, size: number) { return [blank - size, blank + size, blank % size === 0 ? -1 : blank - 1, blank % size === size - 1 ? -1 : blank + 1].filter((value) => value >= 0 && value < size * size); }
function shuffled(size: number) { const board = createBoard(size); let blank = board.length - 1; let last = -1; for (let turn = 0; turn < size * size * 18; turn += 1) { const options = neighbors(blank, size).filter((value) => value !== last); const next = options[Math.floor(Math.random() * options.length)]; [board[blank], board[next]] = [board[next], board[blank]]; last = blank; blank = next; } if (solved(board)) { const next = neighbors(blank, size)[0]; [board[blank], board[next]] = [board[next], board[blank]]; } return board; }

export function PuzzleGame() {
  const { result, finish, resetCompletion } = useGameCompletion("puzzle-bible");
  const [size, setSize] = useState(3); const [board, setBoard] = useState<Tile[]>(() => shuffled(3)); const [moves, setMoves] = useState(0); const [timerOn, setTimerOn] = useState(false); const [seconds, setSeconds] = useState(0);
  const score = Math.max(120, size * size * 45 - moves * 3 - Math.floor(seconds / 5));
  useEffect(() => { if (!timerOn || result) return; const interval = window.setInterval(() => setSeconds((value) => value + 1), 1000); return () => window.clearInterval(interval); }, [result, timerOn]);
  const reset = (nextSize = size) => { setSize(nextSize); setBoard(shuffled(nextSize)); setMoves(0); setSeconds(0); resetCompletion(); };
  const move = (position: number) => { if (result) return; const blank = board.indexOf(null); if (!neighbors(blank, size).includes(position)) return; const next = [...board]; [next[position], next[blank]] = [next[blank], next[position]]; const nextMoves = moves + 1; setBoard(next); setMoves(nextMoves); if (solved(next)) finish({ points: Math.max(120, size * size * 45 - nextMoves * 3 - Math.floor(seconds / 5)), xp: size === 3 ? 110 : 140 }); };
  const formattedTime = `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
  const backgroundFor = (tile: number) => { const row = Math.floor(tile / size); const col = tile % size; const divisor = Math.max(1, size - 1); return { backgroundImage: `url("${sceneUrl}")`, backgroundSize: `${size * 100}% ${size * 100}%`, backgroundPosition: `${(col / divisor) * 100}% ${(row / divisor) * 100}%` }; };
  if (result) return <VictoryPanel title="¡La escena está completa!" description={`Armaste el rompecabezas en ${moves} movimientos${timerOn ? ` y ${formattedTime}` : ""}.`} result={result} points={score} xp={size === 3 ? 110 : 140} onPlayAgain={() => reset()} />;
  return <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="rounded-[1.7rem] bg-white p-4 shadow-card sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-violet">El arca y el arco de esperanza</p><p className="mt-1 text-sm font-bold text-ink/65">Toca una pieza junto al espacio vacío para moverla.</p></div><div className="flex gap-2"><span className="rounded-xl bg-sky px-3 py-2 text-sm font-black text-ink">↔ {moves}</span>{timerOn && <span className="rounded-xl bg-sun/35 px-3 py-2 font-display text-lg font-black text-ink">⏱ {formattedTime}</span>}</div></div><div className={`mx-auto mt-6 grid max-w-2xl gap-1.5 rounded-2xl bg-ink p-2 sm:gap-2 ${size === 3 ? "grid-cols-3" : "grid-cols-4"}`}>{board.map((tile, position) => tile === null ? <div key={`blank-${position}`} className="aspect-square rounded-lg bg-white/10" aria-label="Espacio vacío" /> : <button type="button" key={tile} onClick={() => move(position)} aria-label={`Mover pieza ${tile + 1}`} className="aspect-square rounded-lg outline-none transition-transform hover:scale-[.97] focus-visible:ring-4 focus-visible:ring-sun" style={backgroundFor(tile)} />)}</div></div><aside className="rounded-[1.7rem] bg-[#e9fbf5] p-5 shadow-card"><p className="text-xs font-black uppercase tracking-[.16em] text-leaf">Ajustes</p><label className="mt-4 block text-sm font-bold text-ink">Piezas<select value={size} onChange={(event) => reset(Number(event.target.value))} className="mt-2 h-11 w-full rounded-xl border border-ink/10 bg-white px-3 font-bold outline-none focus:border-violet focus:ring-4 focus:ring-violet/15"><option value={3}>3 × 3 · Inicial</option><option value={4}>4 × 4 · Aventurero</option></select></label><label className="mt-4 flex items-center justify-between rounded-xl bg-white p-3 text-sm font-bold text-ink"><span>Temporizador</span><input type="checkbox" checked={timerOn} onChange={(event) => setTimerOn(event.target.checked)} className="h-5 w-5 accent-violet" /></label><div className="mt-5 rounded-xl bg-white p-4"><p className="text-xs font-black uppercase tracking-wide text-ink/50">Recompensa actual</p><p className="mt-1 font-display text-3xl font-black text-violet">{score}</p><p className="text-xs font-bold text-ink/60">puntos estimados</p></div><button type="button" onClick={() => reset()} className="mt-5 w-full rounded-xl bg-ink px-4 py-3 text-sm font-extrabold text-white hover:bg-violet focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-violet/25">Mezclar de nuevo</button></aside></div>;
}
